### ISSUE TITLE
cannot tap joeyhoer/extras

### ISSUE THREAD

**Issue by ajslater** [joeyhoer/homebrew-extras#3]
```
$ brew tap joeyhoer/extras
==> Tapping joeyhoer/extras
Cloning into '/usr/local/Homebrew/Library/Taps/joeyhoer/homebrew-extras'...
remote: Counting objects: 43, done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 43 (delta 4), reused 21 (delta 2), pack-reused 0
Unpacking objects: 100% (43/43), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/joeyhoer/homebrew-extras/mageconfigsync.rb
mageconfigsync: cannot load such file -- /usr/local/Homebrew/Library/Taps/homebrew/homebrew-php/Abstract/abstract-php-phar
Error: Cannot tap joeyhoer/extras: invalid syntax in tap!
```

**Comment by ajslater** [comment]
I guess your extras tap requires:
```brew tap homebrew/homebrew-php```

**Comment by joeyhoer** [comment]
Yeah… that's an unfortunate side effect of the [mageconfigsync](https://github.com/joeyhoer/homebrew-extras/blob/master/mageconfigsync.rb) formula. It's a phar file and Homebrew doesn't provide an elegant way to install phar files (that I'm aware of), so you have to load the relative path to Homebrew PHP.

If you know of a better way, please let me know! …perhaps I'll separate that into it's own branch/repo at some point. Thanks for reminding me!
